### ISSUE TITLE
Feature: Add function to validate that a float conforms to the encoding scheme

### ISSUE THREAD

**Issue by Paul-Dempsey** [baconpaul/tipsy-encoder#10]
(From PR discussion.)

For robust handling of encoded data in a CV stream, it could be useful to have a function in `binary-to-float` with the signature:

```cpp
bool isValidByteEncoding(float f);
```

This doesn't mean that it is a float resulting from encoding -- only that it is valid in the schema. it may be that this isn't that useful in practice because few floats are outside the schema (not sure about that -- NaNs and infinitites and maybe negative zero), but it's something we can at least use internally in asserts and tests.

**Comment by baconpaul** [comment]
So the schema uses the sign bits and 23 low bits and sets the exponent to a constant below the sign bit.

That means there's two type of valid:

will be GENERATED is any binary value with the exponent
will be PARSED is any float since we don't check the exponent on input

so which one we choose to mean with this is tricky. I think we mean "couldHaveBeenGeneratedByEncoding" which really means "exponent bits are set to what we think".

Also do we want to make decoding a float with the exponent wrong fail? Or assert bad debug state at least? Probably since we use that range for the sentinels in the protocol

**Comment by Paul-Dempsey** [comment]
I think there's a middle approach. I don't think decoding should fail if the floats are little unexpected -- just the current "you get what you get" is ok I think. Although we might have a flag in the decoder that tells the user when some anomalous values were seen. Sentinel values are a valid part of the protocol, but not of the encoding, so there is a place for two levels of validation function -- one that checks known sentinels and another for purely data values.  For users that care about accuracy, they can validate as they wish or check the 'anomalous data' flag. 

Decoding will just fail if sentinels get messed up. Having odd bytes in a message, will often be meh if you're just sending them to a marquee, but something a module may want to pay attention to if it's interpreting the text (e.g. notes notation). The difference is up to the client -- the protocol should merely provide the affordances for clients to implement the policies that make sense for them. maybe when initializing the decoder you can select a policy for anomaly handling (strict, omit-anomalies, relaxed). 

Just thinking out loud...

**Comment by baconpaul** [comment]
So one thing I was thinking overnight but can’t do this am is to check the actual range of the encoded data. We have a test that it is in -10,10 but where is it really? The reason I want to check this is because I kinda want to change the sentinels to all be in -10,10 if we have room so the message will survive clipping. Just adding this comment here so I don’t forget it before some am travel even if it is a bit out of place

**Comment by baconpaul** [comment]
So based on your reaction to #12 we can add two methods

isVakidDataFloat in binary which basically makes sure you are bound between min and max and not inf or nan

isVakidProtocolFloat in protocol makes sure you are a valid data float or you are exactly one of the sentinels 

I think those are the appropriate methods from where we are now.

**Comment by Paul-Dempsey** [comment]
You've understood me perfectly!  The PR with the const, ranges, and tests achieved everything else but the validity functions (unless I skimmed over them)..

**Comment by baconpaul** [comment]
Great I'll add them into that PR also then and push.

**Comment by baconpaul** [comment]
And pushed and tested. Woohoo!
